# Generated by Django 6.0.1 on 2026-02-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avtar',
            field=models.ImageField(upload_to='user_photos/'),
        ),
    ]
